feat core: speed up periodic_task.hpp
Used the following prompt (opencode \+ Claude Sonnet 4):

Use pimpl idiom for utils::PeriodicTask in core/include/userver/utils/periodic\_task.hpp, but use utils::FastPimpl template instead of std::unique\_ptr for
members hiding. You can look at code examples at core/include/userver/engine/io/. For FastPimpl template definition see
universal/include/userver/utils/fast\_pimpl.hpp file. The pair .cpp file for core/include/userver/utils/periodic\_task.hpp iscore/src/utils/periodic\_task.cpp.

cd userver && ctags -R \*/include \*/src
for library in \$(cat files.txt); do tt make \$library -k ; done \|& tee make.log
grep error: make.log \| cut -d/ -f4- \>make2.log

"Fix compilation errors from file make2.log by adding '#include' directive. Either include standard header or user header. The compiled project is written in C\+\+. You can learn which custom header is needed by grepping taxi/uservices/userver/tags file. Do not read entire taxi/uservices/userver/tags file, just grep it. Assume tags file always exists.  Do not change types. Do not change any existing files, write a python script to fix them."
commit_hash:a4e9b1fd144c4363ace804914d990e5e952d62a8