cc core: add missing <fmt/ranges.h> includes
Added missing `#include <fmt/ranges.h>`. Without them the build on macOS fails with multiple `error: no member named 'join' in namespace 'fmt'`.

Issue: https://github.com/userver-framework/userver/issues/689

Tests: протестировано CI

Pull Request resolved: https://github.com/userver-framework/userver/pull/720
commit_hash:12f2d7b53b5b29e186fe8232fc638be5ff167779